### ISSUE TITLE
Name of assignments in group view 

### ISSUE THREAD

**Issue by Darchie4** [ScalableTeaching/ScalableTeaching#126]
The name of the assignments in the group view is all  "Assignment 1" no matter the real name of the assignment

Group view:
https://gyazo.com/4750a8a36daa9f98af707aaf6e29c121
The real names:
https://gyazo.com/d83e4cc5964b0797fd95b6374f0322e7

**Comment by jazerix** [comment]
@Christen97 is this something you can take a look at?
