### ISSUE TITLE
Grading view lost breadcrumbs

### ISSUE THREAD

**Issue by mcamp** [ScalableTeaching/ScalableTeaching#33]
The grading view does not have the breadcrumbs of other views, which I think it is odd because I find the breadcrumbs useful

No breadcrumbs
![image](https://user-images.githubusercontent.com/833197/155381240-b7e663e1-fd1b-4e87-b96f-7d5cb663ab98.png)

Breadcrumbs
![image](https://user-images.githubusercontent.com/833197/155381281-5574d0ce-7cee-4140-bc51-8b2802267a21.png)

**Comment by MagnusHJensen** [comment]
Closing since the grading tab no longer exists.
